version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=YI61TKW/lwz3C5p3iZUU0yNHNNuFrNKk+35npA1uukc=
      - WIREGUARD_ADDRESSES=10.70.74.83/32
      - SERVER_CITIES=Chicago IL
    ports:
      - 9091:9091 # Transmission
      - 9092:8000 # VPN UI
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
  
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - '/data/docker-appdata/transmission/config/:/config'
      - '/data/media/:/data/media:rw'
    # ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - '/data/docker-appdata/deluge/config/:/config'
      - '/data/media/:/data/media:rw'
    # ports:
    #   - 8112:8112
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 58846:58846 #optional
    restart: unless-stopped
  
  tailscale:
    image: 'tailscale/tailscale:latest'
    hostname: media-aq
    container_name: media-aq-ts
    environment:
      - TS_AUTHKEY=tskey-auth-kBU8FShjE521CNTRL-7oL3xHnaGHYbsSwSuAifMYhQ1tEknVNz
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-routes=false
    volumes:
      - 'tailscale-data:/var/lib/tailscale'
      - '/dev/net/tun:/dev/net/tun'
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  bazarr:
    image: 'lscr.io/linuxserver/bazarr:latest'
    container_name: bazarr
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
      # - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - '/data/docker-appdata/bazarr:/config'
      - '/data/media/Movies:/movies'
      - '/data/media/TV:/tv'
      - '/data/media/Downloads:/data/downloads'
      - '/data/media/:/data/media'
    restart: unless-stopped
  lidarr:
    image: 'lscr.io/linuxserver/lidarr:latest'
    container_name: lidarr
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
     # - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - '/data/docker-appdata/lidar:/config'
      - '/data/media/Music:/music'
      - '/data/media/Downloads:/data/downloads'
      - '/data/media/:/data/media'
    restart: unless-stopped
  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: prowlarr
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
     # - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - '/data/docker-appdata/prowlarr:/config'
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
     # - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK_SET=022
    volumes:
      - '/data/docker-appdata/radarr:/config'
      - '/data/media/Movies:/movies'
      - '/data/media/Downloads:/data/downloads'
      - '/data/media/:/data/media'
    restart: unless-stopped
  readarr:
    image: 'lscr.io/linuxserver/readarr:develop'
    container_name: readarr
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
     # - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - '/data/docker-appdata/readarr:/config'
      - '/data/media/Books:/books'
      - '/data/media/Downloads:/data/downloads'
      - '/data/media/:/data/media'
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
     # - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK_SET=022
    volumes:
      - '/data/docker-appdata/sonarr:/config'
      - '/data/media/TV:/tv'
      - '/data/media/Downloads:/data/downloads'
      - '/data/media/:/data/media'
    restart: unless-stopped
volumes:
  tailscale-data:
    driver: local
