# Auto-generated using compose2nix v0.2.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ersatztv-ersatztv" = {
    image = "jasongdove/ersatztv:latest";
    environment = {
      "TZ" = "America/Indinapolis";
    };
    volumes = [
      "/data/docker-appdata/ersatztv/:/root/.local/share/ersatztv:rw"
      "/data/media:/data/media:ro"
    ];
    ports = [
      "8409:8409/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=ersatztv"
      "--network=ersatztv_default"
    ];
  };
  systemd.services."docker-ersatztv-ersatztv" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-ersatztv_default.service"
    ];
    requires = [
      "docker-network-ersatztv_default.service"
    ];
    partOf = [
      "docker-compose-ersatztv-root.target"
    ];
    wantedBy = [
      "docker-compose-ersatztv-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-ersatztv_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ersatztv_default";
    };
    script = ''
      docker network inspect ersatztv_default || docker network create ersatztv_default
    '';
    partOf = [ "docker-compose-ersatztv-root.target" ];
    wantedBy = [ "docker-compose-ersatztv-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ersatztv-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
