# Auto-generated using compose2nix v0.1.9.
{ pkgs, lib, ... }:

{
  # Containers# Auto-generated using compose2nix v0.1.9.
{ pkgs, lib, ... }:

  # Containers
  virtualisation.oci-containers.containers."caddy" = {
    image = "tristonyoder/caddy-custom:latest";
    volumes = [
      "/data/docker-appdata/caddy/david.theyoder.family/Caddyfile:/etc/caddy/Caddyfile:rw"
      "/data/docker-appdata/caddy/david.theyoder.family/config:/config:rw"
      "/data/docker-appdata/caddy/david.theyoder.family/data:/data:rw"
    ];
    ports = [
      "80:80/tcp"
      "443:443/tcp"
      "443:443/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=caddy"
      "--network=caddy_default"
    ];
  };
  systemd.services."docker-caddy" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-caddy_default.service"
    ];
    requires = [
      "docker-network-caddy_default.service"
    ];
    partOf = [
      "docker-compose-caddy-root.target"
    ];
    wantedBy = [
      "docker-compose-caddy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-caddy_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f caddy_default";
    };
    script = ''
      docker network inspect caddy_default || docker network create caddy_default
    '';
    partOf = [ "docker-compose-caddy-root.target" ];
    wantedBy = [ "docker-compose-caddy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-caddy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}

  virtualisation.oci-containers.containers."caddy" = {
    image = "tristonyoder/caddy-custom:latest";
    volumes = [
      "/data/docker-appdata/caddy/david.theyoder.family/Caddyfile:/etc/caddy/Caddyfile:rw"
      "/data/docker-appdata/caddy/david.theyoder.family/config:/config:rw"
      "/data/docker-appdata/caddy/david.theyoder.family/data:/data:rw"
    ];
    ports = [
      "80:80/tcp"
      "443:443/tcp"
      "443:443/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=caddy"
      "--network=caddy_default"
    ];
  };
  systemd.services."docker-caddy" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-caddy_default.service"
    ];
    requires = [
      "docker-network-caddy_default.service"
    ];
    partOf = [
      "docker-compose-caddy-root.target"
    ];
    wantedBy = [
      "docker-compose-caddy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-caddy_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f caddy_default";
    };
    script = ''
      docker network inspect caddy_default || docker network create caddy_default
    '';
    partOf = [ "docker-compose-caddy-root.target" ];
    wantedBy = [ "docker-compose-caddy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-caddy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
