# Bitfocus Companion - Control Software for Streamdecks and Button Panels
# Integrates with 2,800+ modules including video switchers, audio, lighting, and automation
# Auto-generated structure based on compose2nix patterns

{ pkgs, lib, ... }:

{
  # Ensure data directory exists with correct permissions
  # Companion container runs as user "companion" (UID 1000, GID 1000)
  systemd.tmpfiles.rules = [
    "d /data/docker-appdata/companion 0755 1000 1000 -"
  ];

  # Containers
  virtualisation.oci-containers.containers."companion" = {
    image = "ghcr.io/bitfocus/companion/companion:latest";
    volumes = [
      "/data/docker-appdata/companion:/companion:rw"
    ];
    ports = [
      "8880:8000/tcp"    # Web interface (host:container)
      "16622:16622/tcp"  # Companion Satellite (remote USB connections)
      "28492:28492/tcp"  # Module communications
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=companion"
      "--network=portainer_default"
    ];
  };
  
  systemd.services."docker-companion" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-portainer_default.service"
    ];
    requires = [
      "docker-network-portainer_default.service"
    ];
    partOf = [
      "docker-compose-companion-root.target"
    ];
    wantedBy = [
      "docker-compose-companion-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-companion-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix for Bitfocus Companion.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}

