# OpenClaw (Clawbot) - AI assistant with automated updates
# Pre-built Docker image providing AI assistant capabilities with support for multiple providers
# Auto-updates daily and checks for new releases every 6 hours
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."openclaw" = {
    image = "ghcr.io/phioranex/openclaw-docker:latest";
    volumes = [
      "/data/docker-appdata/openclaw/config:/home/node/.openclaw:rw"
      "/data/docker-appdata/openclaw/workspace:/home/node/.openclaw/workspace:rw"
    ];
    ports = [
      "18789:18789/tcp"
    ];
    cmd = [ "gateway" "run" "--allow-unconfigured" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=openclaw"
      "--network=openclaw_default"
    ];
  };
  systemd.services."docker-openclaw" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-openclaw_default.service"
    ];
    requires = [
      "docker-network-openclaw_default.service"
    ];
    partOf = [
      "docker-compose-openclaw-root.target"
    ];
    wantedBy = [
      "docker-compose-openclaw-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-openclaw_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f openclaw_default";
    };
    script = ''
      docker network inspect openclaw_default || docker network create openclaw_default
    '';
    partOf = [ "docker-compose-openclaw-root.target" ];
    wantedBy = [ "docker-compose-openclaw-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-openclaw-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
