# Auto-generated using compose2nix v0.1.9.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."code-server" = {
    image = "linuxserver/code-server:latest";
    environment = {
      PGID = "1000";
      PUID = "1000";
      TZ = "America/Indianapolis";
    };
    volumes = [
      "/data/docker-appdata/codeserver/config:/config:rw"
    ];
    ports = [
      "6443:8443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=code-server"
    ];
  };
  systemd.services."docker-code-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-caddy_default.service"
    ];
    requires = [
      "docker-network-caddy_default.service"
    ];
    partOf = [
      "docker-compose-caddy-root.target"
    ];
    wantedBy = [
      "docker-compose-caddy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-caddy_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f caddy_default";
    };
    script = ''
      docker network inspect caddy_default || docker network create caddy_default
    '';
    partOf = [ "docker-compose-caddy-root.target" ];
    wantedBy = [ "docker-compose-caddy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-caddy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
