# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."planning-poker-planning-poker" = {
    image = "axeleroy/self-host-planning-poker:latest";
    volumes = [
      "planning-poker_planning-poker-data:/data/docker-appdata/planning-poker:rw"
    ];
    ports = [
      "8234:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=planning-poker"
      "--network=planning-poker_default"
    ];
  };
  systemd.services."docker-planning-poker-planning-poker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-planning-poker_default.service"
      "docker-volume-planning-poker_planning-poker-data.service"
    ];
    requires = [
      "docker-network-planning-poker_default.service"
      "docker-volume-planning-poker_planning-poker-data.service"
    ];
    partOf = [
      "docker-compose-planning-poker-root.target"
    ];
    wantedBy = [
      "docker-compose-planning-poker-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-planning-poker_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f planning-poker_default";
    };
    script = ''
      docker network inspect planning-poker_default || docker network create planning-poker_default
    '';
    partOf = [ "docker-compose-planning-poker-root.target" ];
    wantedBy = [ "docker-compose-planning-poker-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-planning-poker_planning-poker-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect planning-poker_planning-poker-data || docker volume create planning-poker_planning-poker-data
    '';
    partOf = [ "docker-compose-planning-poker-root.target" ];
    wantedBy = [ "docker-compose-planning-poker-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-planning-poker-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
