# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."wiki-js-db" = {
    image = "postgres:15-alpine";
    environment = {
      "POSTGRES_DB" = "wiki";
      "POSTGRES_PASSWORD" = "wikijsrocks";
      "POSTGRES_USER" = "wikijs";
    };
    volumes = [
      "wiki-js_db-data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "none";
    extraOptions = [
      "--network-alias=db"
      "--network=wiki-js_default"
    ];
  };
  systemd.services."docker-wiki-js-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wiki-js_default.service"
      "docker-volume-wiki-js_db-data.service"
    ];
    requires = [
      "docker-network-wiki-js_default.service"
      "docker-volume-wiki-js_db-data.service"
    ];
    partOf = [
      "docker-compose-wiki-js-root.target"
    ];
    wantedBy = [
      "docker-compose-wiki-js-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wiki-js-wiki" = {
    image = "ghcr.io/requarks/wiki:2";
    environment = {
      "DB_HOST" = "db";
      "DB_NAME" = "wiki";
      "DB_PASS" = "wikijsrocks";
      "DB_PORT" = "5432";
      "DB_TYPE" = "postgres";
      "DB_USER" = "wikijs";
    };
    ports = [
      "3000:3000/tcp"
    ];
    dependsOn = [
      "wiki-js-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wiki"
      "--network=wiki-js_default"
    ];
  };
  systemd.services."docker-wiki-js-wiki" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wiki-js_default.service"
    ];
    requires = [
      "docker-network-wiki-js_default.service"
    ];
    partOf = [
      "docker-compose-wiki-js-root.target"
    ];
    wantedBy = [
      "docker-compose-wiki-js-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wiki-js_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wiki-js_default";
    };
    script = ''
      docker network inspect wiki-js_default || docker network create wiki-js_default
    '';
    partOf = [ "docker-compose-wiki-js-root.target" ];
    wantedBy = [ "docker-compose-wiki-js-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-wiki-js_db-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect wiki-js_db-data || docker volume create wiki-js_db-data
    '';
    partOf = [ "docker-compose-wiki-js-root.target" ];
    wantedBy = [ "docker-compose-wiki-js-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wiki-js-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
