# Hardware configuration for tristons-desk
# This file should be replaced with the actual hardware-configuration.nix
# generated by nixos-generate-config on the target machine

{ config, lib, pkgs, modulesPath, ... }:

{
  # PLACEHOLDER: This is a template file
  # On the actual machine, run: sudo nixos-generate-config
  # Then copy the generated hardware-configuration.nix to this location
  
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Example hardware configuration - replace with actual values
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];  # or "kvm-amd" for AMD
  boot.extraModulePackages = [ ];

  # Replace with actual filesystem configuration
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-ACTUAL-UUID";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Networking
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  
  # CPU-specific configuration
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # Or for AMD: hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

