# Threadfin - M3U proxy for Plex, Emby, and Jellyfin
# Provides IPTV stream buffering, filtering, and EPG management for media servers
# Auto-generated using compose2nix v0.3.2.
{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."threadfin" = {
    image = "fyb3roptik/threadfin";
    environment = {
      "PUID" = "1001";
      "PGID" = "1001";
      "TZ" = config.time.timeZone;
    };
    volumes = [
      "/data/docker-appdata/threadfin/conf:/home/threadfin/conf:rw"
      "/data/docker-appdata/threadfin/temp:/tmp/threadfin:rw"
    ];
    ports = [
      "34400:34400/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=threadfin"
      "--network=threadfin_default"
    ];
  };
  systemd.services."docker-threadfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-threadfin_default.service"
    ];
    requires = [
      "docker-network-threadfin_default.service"
    ];
    partOf = [
      "docker-compose-threadfin-root.target"
    ];
    wantedBy = [
      "docker-compose-threadfin-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-threadfin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f threadfin_default";
    };
    script = ''
      docker network inspect threadfin_default || docker network create threadfin_default
    '';
    partOf = [ "docker-compose-threadfin-root.target" ];
    wantedBy = [ "docker-compose-threadfin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-threadfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
