# Tunarr - IPTV server that creates linear TV channels from your media library
# Works with Plex, Jellyfin, and Emby as a virtual tuner
{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."tunarr" = {
    image = "ghcr.io/chrisbenincasa/tunarr:latest";
    environment = {
      "TZ" = config.time.timeZone;
    };
    volumes = [
      "/data/docker-appdata/tunarr/:/home/node/app/.tunarr:rw"
      "/data/media:/data/media:ro"
    ];
    ports = [
      "8100:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tunarr"
      "--network=tunarr_default"
    ];
  };

  systemd.services."docker-tunarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-tunarr_default.service"
    ];
    requires = [
      "docker-network-tunarr_default.service"
    ];
    partOf = [
      "docker-compose-tunarr-root.target"
    ];
    wantedBy = [
      "docker-compose-tunarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-tunarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f tunarr_default";
    };
    script = ''
      docker network inspect tunarr_default || docker network create tunarr_default
    '';
    partOf = [ "docker-compose-tunarr-root.target" ];
    wantedBy = [ "docker-compose-tunarr-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-tunarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
