# Auto-generated using compose2nix v0.2.0-pre.
{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."photography_carolineelizabeth-db" = {
    image = "mysql:5.7";
    environmentFiles = [
      config.age.secrets.wordpress-photography-mysql.path
    ];
    environment = {
      MYSQL_DATABASE = "wordpress";
      # MYSQL_PASSWORD loaded from secret file
      # MYSQL_ROOT_PASSWORD loaded from secret file
      MYSQL_USER = "wordpress";
    };
    volumes = [
      "/data/docker-appdata/photography-carolineelizabeth/database:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=photography-carolineelizabeth_default"
    ];
  };
  systemd.services."docker-photography_carolineelizabeth-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-photography-carolineelizabeth_default.service"
    ];
    requires = [
      "docker-network-photography-carolineelizabeth_default.service"
    ];
    partOf = [
      "docker-compose-photography_carolineelizabeth-root.target"
    ];
    wantedBy = [
      "docker-compose-photography_carolineelizabeth-root.target"
    ];
  };
  virtualisation.oci-containers.containers."photography_carolineelizabeth-wordpress" = {
    image = "wordpress:latest";
    environmentFiles = [
      config.age.secrets.wordpress-photography-wp.path
    ];
    environment = {
      WORDPRESS_DB_HOST = "db:3306";
      # WORDPRESS_DB_PASSWORD loaded from secret file
      WORDPRESS_DB_USER = "wordpress";
    };
    volumes = [
      "/data/docker-appdata/photography-carolineelizabeth/wp-backup/:/var/www/html:rw"
    ];
    ports = [
      "1996:80/tcp"
    ];
    dependsOn = [
      "photography_carolineelizabeth-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=photography-carolineelizabeth_default"
    ];
  };
  systemd.services."docker-photography_carolineelizabeth-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-photography-carolineelizabeth_default.service"
    ];
    requires = [
      "docker-network-photography-carolineelizabeth_default.service"
    ];
    partOf = [
      "docker-compose-photography_carolineelizabeth-root.target"
    ];
    wantedBy = [
      "docker-compose-photography_carolineelizabeth-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-photography-carolineelizabeth_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f photography-carolineelizabeth_default";
    };
    script = ''
      docker network inspect photography-carolineelizabeth_default || docker network create photography-carolineelizabeth_default
    '';
    partOf = [ "docker-compose-photography_carolineelizabeth-root.target" ];
    wantedBy = [ "docker-compose-photography_carolineelizabeth-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-photography_carolineelizabeth-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
