# studio.7andco.com - WordPress studio website
# Business website for 7 and Co studio with WordPress CMS and MySQL database
# Auto-generated using compose2nix v0.2.0-pre.
{ config, pkgs, lib, ... }:

let
  # PHP upload limits for the WordPress container. The official image ships
  # upload_max_filesize=2M / post_max_size=8M, which caps media uploads well
  # below what the site needs. Mounted into conf.d so it overrides the defaults.
  phpUploadsIni = pkgs.writeText "studio-7andco-uploads.ini" ''
    file_uploads = On
    upload_max_filesize = 1G
    post_max_size = 1G
    memory_limit = 1G
    max_execution_time = 600
    max_input_time = 600
  '';
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."studio_7andco-db" = {
    # MySQL 5.7 went EOL in Oct 2023. Migrated to 8.0 via dump/restore rather
    # than an in-place upgrade: 8.0 rewrites the data dir irreversibly, so this
    # points at a NEW directory and leaves the 5.7 data untouched. Rollback is
    # reverting this file — see scripts/wordpress-mysql-upgrade.sh.
    image = "mysql:8.0";
    environmentFiles = [
      config.age.secrets.wordpress-studio-mysql.path
    ];
    environment = {
      MYSQL_DATABASE = "wordpress";
      # MYSQL_PASSWORD loaded from secret file
      # MYSQL_ROOT_PASSWORD loaded from secret file
      MYSQL_USER = "wordpress";
    };
    volumes = [
      "/data/docker-appdata/studio-7andco/database-8.0:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=studio_7andco_default"
    ];
  };
  systemd.services."docker-studio_7andco-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-studio_7andco_default.service"
    ];
    requires = [
      "docker-network-studio_7andco_default.service"
    ];
    partOf = [
      "docker-compose-studio_7andco-root.target"
    ];
    wantedBy = [
      "docker-compose-studio_7andco-root.target"
    ];
  };
  virtualisation.oci-containers.containers."studio_7andco-wordpress" = {
    # Pinned to the php8.3 line rather than :latest. Watchtower updates every
    # container on this host unfiltered, so :latest would let it move the site
    # onto a new PHP major without warning — the usual way plugins/themes break.
    # WP core itself lives in the bind-mounted webroot and self-updates, so this
    # pins the runtime only, not the CMS version.
    image = "wordpress:php8.3-apache";
    environmentFiles = [
      config.age.secrets.wordpress-studio-wp.path
    ];
    environment = {
      WORDPRESS_DB_HOST = "db:3306";
      # WORDPRESS_DB_PASSWORD loaded from secret file
      WORDPRESS_DB_USER = "wordpress";
    };
    volumes = [
      "/data/docker-appdata/studio-7andco/data/:/var/www/html:rw"
      "${phpUploadsIni}:/usr/local/etc/php/conf.d/uploads.ini:ro"
    ];
    ports = [
      "7777:80/tcp"
    ];
    dependsOn = [
      "studio_7andco-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=studio_7andco_default"
    ];
  };
  systemd.services."docker-studio_7andco-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-studio_7andco_default.service"
    ];
    requires = [
      "docker-network-studio_7andco_default.service"
    ];
    partOf = [
      "docker-compose-studio_7andco-root.target"
    ];
    wantedBy = [
      "docker-compose-studio_7andco-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-studio_7andco_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f studio_7andco_default";
    };
    script = ''
      docker network inspect studio_7andco_default || docker network create studio_7andco_default
    '';
    partOf = [ "docker-compose-studio_7andco-root.target" ];
    wantedBy = [ "docker-compose-studio_7andco-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-studio_7andco-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
