# Auto-generated using compose2nix v0.2.0-pre.
{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."studio_7andco-db" = {
    image = "mysql:5.7";
    environmentFiles = [
      config.age.secrets.wordpress-studio-mysql.path
    ];
    environment = {
      MYSQL_DATABASE = "wordpress";
      # MYSQL_PASSWORD loaded from secret file
      # MYSQL_ROOT_PASSWORD loaded from secret file
      MYSQL_USER = "wordpress";
    };
    volumes = [
      "/data/docker-appdata/studio-7andco/database:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=studio_7andco_default"
    ];
  };
  systemd.services."docker-studio_7andco-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-studio_7andco_default.service"
    ];
    requires = [
      "docker-network-studio_7andco_default.service"
    ];
    partOf = [
      "docker-compose-studio_7andco-root.target"
    ];
    wantedBy = [
      "docker-compose-studio_7andco-root.target"
    ];
  };
  virtualisation.oci-containers.containers."studio_7andco-wordpress" = {
    image = "wordpress:latest";
    environmentFiles = [
      config.age.secrets.wordpress-studio-wp.path
    ];
    environment = {
      WORDPRESS_DB_HOST = "db:3306";
      # WORDPRESS_DB_PASSWORD loaded from secret file
      WORDPRESS_DB_USER = "wordpress";
    };
    volumes = [
      "/data/docker-appdata/studio-7andco/data/:/var/www/html:rw"
    ];
    ports = [
      "7777:80/tcp"
    ];
    dependsOn = [
      "studio_7andco-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=studio_7andco_default"
    ];
  };
  systemd.services."docker-studio_7andco-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-studio_7andco_default.service"
    ];
    requires = [
      "docker-network-studio_7andco_default.service"
    ];
    partOf = [
      "docker-compose-studio_7andco-root.target"
    ];
    wantedBy = [
      "docker-compose-studio_7andco-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-studio_7andco_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f studio_7andco_default";
    };
    script = ''
      docker network inspect studio_7andco_default || docker network create studio_7andco_default
    '';
    partOf = [ "docker-compose-studio_7andco-root.target" ];
    wantedBy = [ "docker-compose-studio_7andco-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-studio_7andco-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
